# Generated by Django 3.1 on 2021-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Help easily distinguish users and perform queries.Clients are the main type of user', verbose_name='client status'),
        ),
    ]
